services:
  shop-landing-page-frontend:
    depends_on:
      - db
    image: shop-landing-page:local
    container_name: shop-landing-page
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - BACKEND_URL=http://shop-landing-page-backend:3000

    restart: unless-stopped

  shop-landing-page-backend:
    depends_on:
      - db
    image: shop-landing-page-backend:local
    container_name: shop-landing-page-backend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - SERVE_STATIC=/app/frontend/dist
      - CORS_ORIGIN=http://localhost:8001
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} # use this only for postgres
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DB_PROVIDER=postgres
      - GCS_BUCKET=${GCS_BUCKET}
      - GCS_SERVICE_ACCOUNT_EMAIL=${GCS_SERVICE_ACCOUNT_EMAIL:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-sa-key.json
      - SMTP_HOST=mail-eu.smtp2go.com
      - SMTP_PORT=587
      - SMTP_USERNAME=skrond.com
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ${GCP_SA_KEY_PATH:-~/gcp-shop-sa-key.json}:/run/secrets/gcp-sa-key.json:ro
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"