name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      image-name-dockerhub:
        required: true
        type: string
      image-name-github:
        required: true
        type: string
    secrets:
      docker-hub-username:
        required: true
      docker-hub-token:
        required: true
      github-token:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        registry:
          - "ghcr.io"
          - "docker.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ matrix.registry }}
        if: matrix.registry == 'ghcr.io' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Log into registry ${{ matrix.registry }}
        if: matrix.registry == 'docker.io' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.docker-hub-username }}
          password: ${{ secrets.docker-hub-token }}

      - name: Extract Docker metadata (DockerHub)
        id: meta-dockerhub
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.registry }}/${{ inputs.image-name-dockerhub }}

      - name: Extract Docker metadata (GHCR)
        id: meta-ghcr
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.registry }}/${{ inputs.image-name-github }}

      - name: Build and push Docker image to Docker Hub
        if: matrix.registry == 'docker.io' && github.event_name != 'pull_request'
        id: build-and-push-dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-dockerhub.outputs.tags }}
          labels: ${{ steps.meta-dockerhub.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image to GHCR
        if: matrix.registry == 'ghcr.io' && github.event_name != 'pull_request'
        id: build-and-push-ghcr
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-ghcr.outputs.tags }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
