name: Push to registries

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    permissions:
        contents: read
        packages: write
        id-token: write
    with:
      image-name-dockerhub: bobaklabs/dropper-frontend
      image-name-github: tscrond/dropper-frontend
    secrets:
        docker-hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker-hub-token: ${{ secrets.DOCKERHUB_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
